-- ============================================================
-- NØVA LEAGUE — Script de criação das tabelas no Supabase
-- Rode isso em: Supabase > SQL Editor > New query > Run
-- ============================================================
-- Atenção aos nomes entre aspas duplas (ex: "gameId"): o código
-- JavaScript do site usa esses nomes em camelCase EXATAMENTE
-- assim. Se você criar as colunas sem aspas, o Postgres converte
-- tudo para minúsculo e o site para de encontrar os campos
-- (o mesmo tipo de bug silencioso do problema original).

create table if not exists public.jogadores (
  id bigint generated by default as identity primary key,
  nick text not null,
  "gameId" text not null unique,
  password text,
  status text not null default 'normal',
  kills integer not null default 0,
  "matchesCount" integer not null default 0,
  earnings numeric not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.partidas (
  id bigint generated by default as identity primary key,
  number text not null,
  "playerId" bigint references public.jogadores(id) on delete set null,
  "playerGameId" text not null,
  "playerNick" text not null,
  date text,
  kills integer not null default 0,
  pos integer not null default 1,
  total numeric not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.cupons (
  id bigint generated by default as identity primary key,
  code text not null,
  discount text not null,
  valid text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.mensagens (
  id bigint generated by default as identity primary key,
  "recipientId" text not null,
  text text not null,
  date text,
  "readBy" jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

-- ============================================================
-- Row Level Security (RLS)
-- O site NÃO usa o sistema de login do Supabase (Auth) — o login
-- de jogador e de ADM são checados manualmente no JavaScript.
-- Isso significa que todo acesso ao banco acontece com a chave
-- "anon". Por isso liberamos acesso total pra essa chave abaixo.
--
-- ⚠️ Consequência importante: qualquer pessoa que abrir o código-fonte
-- do site (Ctrl+U) e pegar a SUPABASE_ANON_KEY consegue ler e
-- editar essas tabelas diretamente pela API do Supabase — inclusive
-- as senhas dos jogadores, que hoje são salvas em TEXTO PURO.
-- Para um campeonato informal isso costuma ser aceitável, mas se
-- quiser mais segurança no futuro, vale migrar para o Supabase Auth
-- e políticas de RLS restritas por usuário.
-- ============================================================

alter table public.jogadores enable row level security;
alter table public.partidas enable row level security;
alter table public.cupons enable row level security;
alter table public.mensagens enable row level security;

create policy "allow all - jogadores" on public.jogadores
  for all using (true) with check (true);

create policy "allow all - partidas" on public.partidas
  for all using (true) with check (true);

create policy "allow all - cupons" on public.cupons
  for all using (true) with check (true);

create policy "allow all - mensagens" on public.mensagens
  for all using (true) with check (true);
